//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.21 at 07:00:05 PM CLT 
//


package cl.moit.ws.bcentral;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for internetSeriesInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="internetSeriesInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="seriesId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="frequency" type="{http://web.service.sdmx.sdms.sungard.com/}frequency" minOccurs="0"/>
 *         &lt;element name="frequencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="observed" type="{http://web.service.sdmx.sdms.sungard.com/}observed" minOccurs="0"/>
 *         &lt;element name="observedCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="spanishTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="englishTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="firstObservation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastObservation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="updatedAt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="createdAt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "internetSeriesInfo", namespace = "http://web.service.sdmx.sdms.sungard.com/", propOrder = {
    "seriesId",
    "frequency",
    "frequencyCode",
    "observed",
    "observedCode",
    "spanishTitle",
    "englishTitle",
    "firstObservation",
    "lastObservation",
    "updatedAt",
    "createdAt"
})
public class InternetSeriesInfo {

    protected String seriesId;
    protected Frequency frequency;
    protected String frequencyCode;
    protected Observed observed;
    protected String observedCode;
    protected String spanishTitle;
    protected String englishTitle;
    protected String firstObservation;
    protected String lastObservation;
    protected String updatedAt;
    protected String createdAt;

    /**
     * Gets the value of the seriesId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeriesId() {
        return seriesId;
    }

    /**
     * Sets the value of the seriesId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeriesId(String value) {
        this.seriesId = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link Frequency }
     *     
     */
    public Frequency getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Frequency }
     *     
     */
    public void setFrequency(Frequency value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the frequencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequencyCode() {
        return frequencyCode;
    }

    /**
     * Sets the value of the frequencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequencyCode(String value) {
        this.frequencyCode = value;
    }

    /**
     * Gets the value of the observed property.
     * 
     * @return
     *     possible object is
     *     {@link Observed }
     *     
     */
    public Observed getObserved() {
        return observed;
    }

    /**
     * Sets the value of the observed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Observed }
     *     
     */
    public void setObserved(Observed value) {
        this.observed = value;
    }

    /**
     * Gets the value of the observedCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservedCode() {
        return observedCode;
    }

    /**
     * Sets the value of the observedCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservedCode(String value) {
        this.observedCode = value;
    }

    /**
     * Gets the value of the spanishTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpanishTitle() {
        return spanishTitle;
    }

    /**
     * Sets the value of the spanishTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpanishTitle(String value) {
        this.spanishTitle = value;
    }

    /**
     * Gets the value of the englishTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnglishTitle() {
        return englishTitle;
    }

    /**
     * Sets the value of the englishTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnglishTitle(String value) {
        this.englishTitle = value;
    }

    /**
     * Gets the value of the firstObservation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstObservation() {
        return firstObservation;
    }

    /**
     * Sets the value of the firstObservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstObservation(String value) {
        this.firstObservation = value;
    }

    /**
     * Gets the value of the lastObservation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastObservation() {
        return lastObservation;
    }

    /**
     * Sets the value of the lastObservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastObservation(String value) {
        this.lastObservation = value;
    }

    /**
     * Gets the value of the updatedAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets the value of the updatedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedAt(String value) {
        this.updatedAt = value;
    }

    /**
     * Gets the value of the createdAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the value of the createdAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedAt(String value) {
        this.createdAt = value;
    }

}
