//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.21 at 07:00:05 PM CLT 
//


package cl.moit.ws.bcentral;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cl.moit.ws.bcentral package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cl.moit.ws.bcentral
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FameNode }
     * 
     */
    public FameNode createFameNode() {
        return new FameNode();
    }

    /**
     * Create an instance of {@link ArrayOfInternetSeriesInfo }
     * 
     */
    public ArrayOfInternetSeriesInfo createArrayOfInternetSeriesInfo() {
        return new ArrayOfInternetSeriesInfo();
    }

    /**
     * Create an instance of {@link GetSeriesResponse }
     * 
     */
    public GetSeriesResponse createGetSeriesResponse() {
        return new GetSeriesResponse();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link SearchSeriesResponse }
     * 
     */
    public SearchSeriesResponse createSearchSeriesResponse() {
        return new SearchSeriesResponse();
    }

    /**
     * Create an instance of {@link GetSeries }
     * 
     */
    public GetSeries createGetSeries() {
        return new GetSeries();
    }

    /**
     * Create an instance of {@link InternetSeriesInfo }
     * 
     */
    public InternetSeriesInfo createInternetSeriesInfo() {
        return new InternetSeriesInfo();
    }

    /**
     * Create an instance of {@link Obs }
     * 
     */
    public Obs createObs() {
        return new Obs();
    }

    /**
     * Create an instance of {@link FameSeries }
     * 
     */
    public FameSeries createFameSeries() {
        return new FameSeries();
    }

    /**
     * Create an instance of {@link Respuesta }
     * 
     */
    public Respuesta createRespuesta() {
        return new Respuesta();
    }

    /**
     * Create an instance of {@link SearchSeries }
     * 
     */
    public SearchSeries createSearchSeries() {
        return new SearchSeries();
    }

    /**
     * Create an instance of {@link ArrayOfFameSeries }
     * 
     */
    public ArrayOfFameSeries createArrayOfFameSeries() {
        return new ArrayOfFameSeries();
    }

    /**
     * Create an instance of {@link SeriesKey }
     * 
     */
    public SeriesKey createSeriesKey() {
        return new SeriesKey();
    }

}
