//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.21 at 07:00:05 PM CLT 
//


package cl.moit.ws.bcentral;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for obs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="obs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="indexDateString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="seriesKey" type="{http://web.service.sdmx.sdms.sungard.com/}seriesKey" minOccurs="0"/>
 *         &lt;element name="statusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obs", namespace = "http://web.service.sdmx.sdms.sungard.com/", propOrder = {
    "indexDateString",
    "seriesKey",
    "statusCode",
    "value"
})
public class Obs {

    protected String indexDateString;
    protected SeriesKey seriesKey;
    protected String statusCode;
    protected double value;

    /**
     * Gets the value of the indexDateString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexDateString() {
        return indexDateString;
    }

    /**
     * Sets the value of the indexDateString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexDateString(String value) {
        this.indexDateString = value;
    }

    /**
     * Gets the value of the seriesKey property.
     * 
     * @return
     *     possible object is
     *     {@link SeriesKey }
     *     
     */
    public SeriesKey getSeriesKey() {
        return seriesKey;
    }

    /**
     * Sets the value of the seriesKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeriesKey }
     *     
     */
    public void setSeriesKey(SeriesKey value) {
        this.seriesKey = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the value property.
     * 
     */
    public double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(double value) {
        this.value = value;
    }

}
