//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.21 at 07:00:05 PM CLT 
//


package cl.moit.ws.bcentral;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for observed.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="observed">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="UNDEFINED"/>
 *     &lt;enumeration value="SUMMED"/>
 *     &lt;enumeration value="LOW"/>
 *     &lt;enumeration value="HIGH"/>
 *     &lt;enumeration value="END"/>
 *     &lt;enumeration value="BEGINNING"/>
 *     &lt;enumeration value="AVERAGED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "observed", namespace = "http://web.service.sdmx.sdms.sungard.com/")
@XmlEnum
public enum Observed {

    UNDEFINED,
    SUMMED,
    LOW,
    HIGH,
    END,
    BEGINNING,
    AVERAGED;

    public String value() {
        return name();
    }

    public static Observed fromValue(String v) {
        return valueOf(v);
    }

}
